### PR TITLE
fix(lfs-detection): take into account files without patch

### LINKED ISSUE #135: Action ALWAYS reports "The following file(s) are tracked in LFS and were likely accidentally checked in:" for PDF files even if properly stored in LFS
**Describe the bug**
For Pull Requests that contain pdf files, even when the pdf is properly added through LFS, the action reports : 

```
## :warning: Possible file(s) that should be tracked in LFS detected :warning:
        
        The following file(s) are tracked in LFS and were likely accidentally checked in:

        filename.pdf
      
```

### Initial state
1. In a git repo with LFS properly configured, and `.gitattributes` such as 
 ```
*.png filter=lfs diff=lfs merge=lfs -text
*.pdf filter=lfs diff=lfs merge=lfs -text
*.woff filter=lfs diff=lfs merge=lfs -text
*.woff2 filter=lfs diff=lfs merge=lfs -text
*.ico filter=lfs diff=lfs merge=lfs -text

 ```
2. with a GitHub Actions workflow like : 
```yaml
name: LFS-Checker

on:
  pull_request:
  workflow_dispatch: # to run it manually

jobs:
  lfs-checking:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.5
        with:
          lfs: false

      - name: LFS Warning
        uses: actionsdesk/lfs-warning@v3.1
```

### Repro steps:
1. Create a branch, and add a pdf file in it, properly adding it to LFS
2. Push the branch and create a PR
3. Wait for the action workflow to be executed

### Observed behavior:

A comment is added to the PR, and the action is marked as failed : 

image

## Expected behavior
There should not be any warning, and the "PR-check" should be green, given that the pdf file is properly added in LFS.

## Screenshots

GitHub properly reports that the file is stored in LFS when navigating to the file: 
image

## Additional context
With my colleague @davidlj95 we tried to investigate a bit more and noticed a few things : 

- GitHub UI : **Different behavior for `.pdf` files**, compared to other binary files like `.mp4` or `.png`

In the GitHub UI, in a PR that contains `.mp4` or `.png` files added to LFS, the GitHub PR `file` view shows "Git LFS file not shown" : 

image

image

For PDFs, instead it shows "Binary file not shown" : 

image

- GitHub API : **`.pdf` files have no `patch` property** in the response to `GET https://api.github.com/repos/{org}/{repo}/pulls/{pr-id}}/files`

In a PR that adds a `png` and a `pdf` file (added in LFS), 

```curl
curl -H "Authorization: token MY_SECRET_TOKEN" -X GET https://api.github.com/repos/koa-health/mindset-website/pulls/39/files
```

returns

```json
[
  {
    "sha": "256a6025de6227c29ab634ff8f85affa413d72c2",
    "filename": "website/dummy.pdf",
    "status": "added",
    "additions": 0,
    "deletions": 0,
    "changes": 0,
    "blob_url": "https://github.com/koa-health/mindset-website/blob/e1ade945635fdad92b716e1f1aba9b7b8f4d1778/website%2Fdummy.pdf",
    "raw_url": "https://github.com/koa-health/mindset-website/raw/e1ade945635fdad92b716e1f1aba9b7b8f4d1778/website%2Fdummy.pdf",
    "contents_url": "https://api.github.com/repos/koa-health/mindset-website/contents/website%2Fdummy.pdf?ref=e1ade945635fdad92b716e1f1aba9b7b8f4d1778"
  },
  {
    "sha": "68b76bda66713a7c945ee4fdb4c470b639dbe3c9",
    "filename": "website/dummy.png",
    "status": "added",
    "additions": 3,
    "deletions": 0,
    "changes": 3,
    "blob_url": "https://github.com/koa-health/mindset-website/blob/e1ade945635fdad92b716e1f1aba9b7b8f4d1778/website%2Fdummy.png",
    "raw_url": "https://github.com/koa-health/mindset-website/raw/e1ade945635fdad92b716e1f1aba9b7b8f4d1778/website%2Fdummy.png",
    "contents_url": "https://api.github.com/repos/koa-health/mindset-website/contents/website%2Fdummy.png?ref=e1ade945635fdad92b716e1f1aba9b7b8f4d1778",
    "patch": "@@ -0,0 +1,3 @@\n+version https://git-lfs.github.com/spec/v1\n+oid sha256:fa3be2769d3074bc9c5a31a9039f55c9109988e1b3ea4e99731058b0497146e0\n+size 54967"
  }
]
```

note how the entry for the `png` file contains a `patch` property, with the expected "flag" for LFS ... but the `pdf` entry simply has no `patch` property. 

## Probable Root cause of the issue
Based on lack of `patch` property, this part of the code is misbehaving : 

https://github.com/ActionsDesk/lfs-warning/blob/6090ed546050b18e4341e8decc0805d33572fb65/src/index.ts#L52-L55

and `isStoredInLFS` ends up as `false` for PDFs, even if they are properly stored.

## Possible fix
For PDFs, the `patch` property is missing, so we can't rely on it to know whether the "lfs flag" is set or not ... but this information can be obtained through other means. 

Given the response to the "get files for pull request" API call (see above), we have the `sha` of the commit ... from there we can use the "git Blob" API to retrieve the corresponsing contents of the file. 

(it turns out in the current implementation of the action, we are already fetching this information : 

https://github.com/ActionsDesk/lfs-warning/blob/6090ed546050b18e4341e8decc0805d33572fb65/src/index.ts#L184

)

If we do that API call, we get something like : 

```
curl -H "Authorization: token MY_SECRET_TOKEN" -X GET https://api.github.com/repos/koa-health/mindset-website/git/blobs/256a6025de6227c29ab634ff8f85affa413d72c2
```

```json
{
  "sha": "256a6025de6227c29ab634ff8f85affa413d72c2",
  "node_id": "MDQ6QmxvYjQwMzU2MDc5MToyNTZhNjAyNWRlNjIyN2MyOWFiNjM0ZmY4Zjg1YWZmYTQxM2Q3MmMy",
  "size": 130,
  "url": "https://api.github.com/repos/koa-health/mindset-website/git/blobs/256a6025de6227c29ab634ff8f85affa413d72c2",
  "content": "dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0aHViLmNvbS9zcGVjL3YxCm9p\nZCBzaGEyNTY6M2RmNzlkMzRhYmJjYTk5MzA4ZTc5Y2I5NDQ2MWMxODkzNTgy\nNjA0ZDY4MzI5YTQxZmQ0YmVjMTg4NWU2YWRiNApzaXplIDEzMjY0Cg==\n",
  "encoding": "base64"
}
```

And if we look at the content end decode it (base 64 decode)

```
> echo 'dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0aHViLmNvbS9zcGVjL3YxCm9p\nZCBzaGEyNTY6M2RmNzlkMzRhYmJjYTk5MzA4ZTc5Y2I5NDQ2MWMxODkzNTgy\nNjA0ZDY4MzI5YTQxZmQ0YmVjMTg4NWU2YWRiNApzaXplIDEzMjY0Cg==\n' | base64 -d

version https://git-lfs.github.com/spec/v1
oid sha256:3df79d34abbca99308e79cb94461c1893582604d68329a41fd4bec1885e6adb4
size 13264
```

we can retrieve the necessary information to know that this file is indeed stored in LFS.

So it seems like a possible approach to address this issue is to either : 
- no longer look at the `patch` property, and instead ALWAYS look at the `content` of the blob
- or ... use the `patch` property when it's available, and if it's not, look at the content of the blob

I hope this helps :)

### PR DESCRIPTION
**Pull request by davidlj95**
### Description
Fix #135  issue with PDF files.

#### Issue

For PDF files, seems that the `patch` field from the PR list files API is not there. Therefore, the check to see if it is stored in LFS or not fails

https://github.com/davidlj95/lfs-warning/blob/5d972cfa450bec5b14e8e307a190c0b9dada7c26/src/index.ts#L53-L55

#### Proposed solution

Use the `content` field from the get blob API call for those files without `patch`. If file contents (`base64` encoded, as per docs) start with the Git LFS usual file contents (`version https://git-lfs`...) then it's very probably properly stored in Git LFS

#### Tests
- GH Action running with latest version 3.1 doesn't work with PDF Files: https://github.com/davidlj95/lfs-warning-test/pull/1
- GH Action running with fixed version works with PDF files: https://github.com/davidlj95/lfs-warning-test/pull/3

### CODE REVIEW

**Comment by davidlj95** [comment]
❓  Unsure about why diff in `index.js` is so big 🤔  I just did `npm run package` to generate it. Maybe because using `Buffer`?

File: src/index.ts [hunk 1]
```diff
@@ -10,6 +10,14 @@ const context = github.context;
 const {repo} = context;
 const event_type = context.eventName;
 
+const lfsFileContentStart = 'version https://git-lfs.github.com/spec/v1';
+const lfsFileContentStartInBase64 = Buffer.from(
```
Comment (tsimbalar) [inline src/index.ts:14]: nit: maybe less intent revealing, but could we just do : 

```suggestion
const lfsFileContentStartInBase64 = 'dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0a';
```

or some "long-enough" prefix that the chances that a "non-LFS" files starts with this are extremely low ?

File: src/index.ts [hunk 2]
```diff
@@ -50,9 +58,20 @@ async function run() {
...
+            isStoredInLFS = Boolean(
+              file.patch.includes('version https://git-lfs.github.com/spec/v1')
+            );
+          } else if (file.filecontents) {
+            // For PDF files, seems GitHub doesn't have the .patch property set
+            // in the API response. Reading file contents instead
+            // https://github.com/ActionsDesk/lfs-warning/issues/135
+            isStoredInLFS = file.filecontents.startsWith(
+              lfsFileContentStartInBase64
+            );
```
Comment (tsimbalar) [inline src/index.ts:72]: nit: not 100% sure this causes any change of behavior ? 🤔 

i.e. if we look at `patch` only, then I guess we'd report a "this file should be in LFS" only in the PR that introduces this new file (i.e. `patch` will contain the newly added first line with `version https:/....` ... in the future, updates to that same file will still have this `version https/...` prefix, so the `version https/....` will maybe not appear in `patch` as it's an "unchanged" part of the existing file)

By looking at `filecontents`, we always look at the full content of the file "as per the branch" of this PR ... which means this would report both new files, and changes to already existing files ... 

It's probably not a big issue though, and maybe my assumptions are wrong 🙃

File: src/index.ts [hunk 3]
```diff
@@ -50,9 +58,20 @@ async function run() {
         ).stdout.includes('filter: lfs');
 
         if (shouldBeStoredInLFS) {
-          const isStoredInLFS = Boolean(
-            file.patch?.includes('version https://git-lfs.github.com/spec/v1')
-          );
+          let isStoredInLFS = false;
+          if (file.patch) {
+            isStoredInLFS = Boolean(
+              file.patch.includes('version https://git-lfs.github.com/spec/v1')
```
Comment (tsimbalar) [inline src/index.ts:64]: nit: should this re-use the constant `lfsFileContentStart` we have at the top ? 

```suggestion
              file.patch.includes(lfsFileContentStart)
```

File: src/index.ts [hunk 4]
```diff
@@ -50,9 +58,20 @@ async function run() {
         ).stdout.includes('filter: lfs');
 
         if (shouldBeStoredInLFS) {
-          const isStoredInLFS = Boolean(
-            file.patch?.includes('version https://git-lfs.github.com/spec/v1')
-          );
+          let isStoredInLFS = false;
+          if (file.patch) {
```
Comment (tsimbalar) [inline src/index.ts:62]: is it possible that `patch` would be _falsy_ , but still present ?
Should it be a more explicit check like 

```suggestion
          if (file.patch === undefined) {
```

?

File: src/index.ts (hunk 3 above)
Comment (davidlj95) [reply src/index.ts]: oops, yeap!

done in 37d29229f497b4d749be453a83f2dda1bd222d64

File: src/index.ts (hunk 1 above)
Comment (davidlj95) [reply src/index.ts:14]: Hmm I'd go with that to be more intent revealing as you say (otherwise that looks like magic string :P )

not very happy with the magic slice as without context can be a bit obscure to understand I think the main idea of: look for this string in base64 remains

File: src/index.ts (hunk 2 above)
Comment (davidlj95) [reply src/index.ts]: yeah, it's a bit weird because patch in updates to a file shouldn't contain that version line if hasn't changed. however, from experience, seems it works: https://github.com/davidlj95/lfs-warning-test/pull/4

no idea why tho

File: src/index.ts (hunk 4 above)
Comment (davidlj95) [reply src/index.ts:62]: hmm I wanted to contemplate `null` & `undefined` at same time just in case at some point GitHub API changes and returns `patch: null` when no patch shall be returned & `== undefined | null` was a bit verbose

**Comment by ppremk** [comment]
👋🏽  @davidlj95 @tsimbalar thank you for the contribution 💖 Apologies for not getting back ASAP. May I suggest that we resolve the conversations before the approval please? This will allow for a recorded audit on the decision we had taken for folks who may be following along. Also please ping me in here once it is resolved. I will be able to do the next steps 🙇🏽

**Comment by ppremk** [comment]
@davidlj95 @tsimbalar is there anything I can help to get this moving? 🙂

**Comment by davidlj95** [comment]
> @davidlj95 @tsimbalar is there anything I can help to get this moving? 🙂

Hi @ppremk ! Thanks to you 😊 

No worries, as you've seen, wasn't something urgent anyway :P Sorry for disconnecting about this a bit. 

We just talked and resolved conversations. Will rebase, generate the new `index.js` and I think it will be ready to go 🚀

**Comment by davidlj95** [comment]
☝️  Done in b3077e63daae36db0415d1aa061ebafb8430a4e0

**Review by ppremk — APPROVED** [review]
@davidlj95 Let's :shipit: feel free to merge and ping me. I will proceed to cut a new release

**Comment by tsimbalar** [comment]
@davidlj95 can you merge it :P :P

**Comment by ppremk** [comment]
Merging on behalf

**Comment by tsimbalar** [comment]
> Merging on behalf

Thanks @ppremk  👍 

What is the next step for this change to be part of the next release ? :)

**Comment by ppremk** [comment]
@tsimbalar forgive me for missing out on this notification. Was OOO and travelling. I have blocked time to cut a new a release and add some release notes pointing to this Issue/PR. 🙇🏽 Thank you for your patience and continued support.

**Comment by tsimbalar** [comment]
Hi @ppremk is there any chance you can publish a release in the near future ? :)
